### ISSUE TITLE
[Bug]docs version page display not centered

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis-website#193]
https://linkis.apache.org/versions/
https://linkis.apache.org/zh-CN/versions/ 

![image](https://user-images.githubusercontent.com/7869972/158817826-0dcb4efa-9552-46d9-ac3e-62fddf3ea822.png)

**Comment by TuhinBanerjee31** [comment]
Hello. I'm a beginner and new to the community.  Can I get this issue to work on ? Thank You .

**Comment by casionone** [comment]
> Hello. I'm a beginner and new to the community. Can I get this issue to work on ? Thank You .

Sorry I missed this message. If you are interested, just do it . 
Contribution Guidelines Reference: https://linkis.apache.org/community/how-to-contribute-to-website
