### ISSUE TITLE
[Improvement]Download page optimization to improve user experience

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis-website#257]
- ~~Add  "how to compile" or "how to package" guidelines, which are convenient for users to compile intuitively and quickly~~ finished 
- ~~Add "verify the releases" guidelines~~ finished
- Table layout adjustment, try to avoid the crowded list content displayed
![image](https://user-images.githubusercontent.com/7869972/168205510-801bda76-beee-42d7-a185-b89424ad2e61.png)

**Comment by Beacontownfc** [comment]
I think I can fix it
