### ISSUE TITLE
[Bug]Problem with blog display in menu bar

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis-website#267]
![image](https://user-images.githubusercontent.com/7869972/170164105-e507c8bb-04af-4519-8200-4d39a855ff4b.png)

It should be highlighted when clicked,such as 
![image](https://user-images.githubusercontent.com/7869972/170164522-7d127129-8b33-4291-8514-4ec115c24531.png)

**Comment by Lucknicking** [comment]
I want to fix this bug.
