### ISSUE TITLE
[Improvement] Linkis website checks

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis-website#269]
As show in  https://whimsy.apache.org/pods/project/linkis
the linkis website with some problems and needs to be fixed
You can refer to the websites of other projects https://whimsy.apache.org/pods/check/uri 

![image](https://user-images.githubusercontent.com/7869972/170166241-18a91e4c-4c10-48b0-8b4d-c4f9da8abf43.png)

**Comment by Beacontownfc** [comment]
I think I can fix it, please assign it to me

**Comment by Beacontownfc** [comment]
To fix this issue, just change the published URL in the yml file: https://svn.apache.org/repos/asf/incubator/public/trunk/content/podlings/linkis.yml
