### ISSUE TITLE
[Community] Maturity Assessment for Linkis

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis-website#564]
[Maturity Assessment for Linkis](https://github.com/apache/incubator-linkis-website/blob/dev/maturity.md)
 
 Feel free to discuss and leave your comment.

**Comment by jacktao007** [comment]
good

**Comment by utopianet** [comment]
+1
I reviewed the maturity self-assessment of Apache Linkis above. I think the status of this assessment is authentic.

**Comment by CCweixiao** [comment]
+1
I think it's comprehensive, nothing that might need to be changed for now.
