### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-linkis-website#752]
https://github.com/apache/linkis-website/blob/ab2f1c5a88b3328775fab885321a739dd34f6aa0/doap.rdf#L43

The previous value was correct

**Comment by casionone** [comment]
> https://github.com/apache/linkis-website/blob/ab2f1c5a88b3328775fab885321a739dd34f6aa0/doap.rdf#L43
> 
> The previous value was correct

ok, I fixed
